"""SEC (Simple Event Correlator) format exporter for RedSEC.

Converts RedSecEvent lists and AttackChain objects into .conf files
that can be consumed directly by Risto Vaarandi's SEC tool.

SEC reference: https://github.com/simple-evcorr/sec
"""

import os
import re
from datetime import datetime, timezone

from redsec.models.chain import AttackChain
from redsec.models.event import RedSecEvent

# Version string embedded in generated file headers.
_REDSEC_VERSION = "1.0.0"

# ---------------------------------------------------------------------------
# Module-level constant: standard file header written to every .conf output.
# ---------------------------------------------------------------------------
SEC_HEADER = """\
##############################################################################
# Generated by RedSEC {version}
# https://github.com/simple-evcorr/sec
#
# RedSEC is a red team log aggregation and correlation tool.
# This file is intended for use with SEC (Simple Event Correlator)
# by Risto Vaarandi.
#
# SEC project : https://github.com/simple-evcorr/sec
# RedSEC docs : see docs/THEORETICAL_BACKGROUND.md
#
# Do not edit by hand — regenerate via: redsec export --format sec
##############################################################################
""".format(version=_REDSEC_VERSION)


class SecExporter:
    """Export RedSecEvent lists and AttackChains to SEC .conf format.

    Each exported file is a valid SEC configuration that can be fed to
    the SEC daemon with::

        sec --conf=output.conf --input=logfile.log

    SEC rule types used:

    * ``Single``     — fires once per matching log line (one per event).
    * ``EventGroup`` — fires when a set of sub-patterns have all matched
                       within a time window (chain completion rule).
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def export_events(self, events: list[RedSecEvent], output_path: str) -> str:
        """Write a SEC .conf file containing one rule per event.

        Each event is translated into a ``type=Single`` SEC rule whose
        pattern matches the event's SEC log line format
        (``TIMESTAMP TOOL EVENT_TYPE TARGET DESCRIPTION``).

        Args:
            events: List of RedSecEvent instances to export.
            output_path: Destination file path for the .conf output.

        Returns:
            The absolute path of the written file.

        Raises:
            OSError: If the output file cannot be written.
        """
        lines: list[str] = [SEC_HEADER]
        lines.append(self._generation_comment())
        lines.append("")

        for idx, event in enumerate(events, start=1):
            lines.append(f"# Event {idx}: {event.event_type} on {event.target}")
            lines.extend(self._single_rule(event))
            lines.append("")

        return self._write(output_path, lines)

    def export_chain(self, chain: AttackChain, output_path: str) -> str:
        """Write a SEC .conf file for a single AttackChain.

        The file contains:

        1. A header comment with chain metadata (name, severity, MITRE
           techniques, event count, time range).
        2. One ``type=Single`` rule per event in the chain.
        3. A final ``type=EventGroup`` rule that fires when all events
           in the chain have been observed, signalling chain completion.

        Args:
            chain: The AttackChain to export.
            output_path: Destination file path for the .conf output.

        Returns:
            The absolute path of the written file.

        Raises:
            OSError: If the output file cannot be written.
        """
        severity = chain.severity if isinstance(chain.severity, str) else chain.severity.value
        techniques = ", ".join(chain.mitre_techniques) if chain.mitre_techniques else "N/A"

        lines: list[str] = [SEC_HEADER]
        lines.append(self._generation_comment())
        lines.append("")
        lines.append(f"# Chain   : {chain.name}")
        lines.append(f"# Severity: {severity.upper()}")
        lines.append(f"# MITRE   : {techniques}")
        lines.append(f"# Events  : {len(chain.events)}")
        lines.append(f"# Start   : {chain.start_time.isoformat()}")
        lines.append(f"# End     : {chain.end_time.isoformat()}")
        lines.append("")

        event_blocks: list[tuple[str, str]] = []
        for idx, event in enumerate(chain.events, start=1):
            lines.append(f"# Step {idx}: {event.event_type} on {event.target}")
            lines.extend(self._single_rule(event, chain_name=chain.name))
            lines.append("")
            tool = event.tool if isinstance(event.tool, str) else event.tool.value
            etype = event.event_type if isinstance(event.event_type, str) else event.event_type.value
            event_blocks.append((
                self._build_pattern(tool, etype, event.target),
                self._rule_desc(event, chain.name),
            ))

        # Chain-completion EventGroup rule.
        lines.append("# Chain completion — fires when all steps above have matched")
        lines.extend(self._eventgroup_rule(chain, event_blocks))
        lines.append("")

        return self._write(output_path, lines)

    def export_all(self, chains: list[AttackChain], output_path: str) -> str:
        """Export all AttackChains into a single SEC .conf file.

        Chains are written sequentially, each preceded by a separator
        comment.  A global file header includes the RedSEC version and
        the UTC generation timestamp.

        Args:
            chains: List of AttackChain instances to export.
            output_path: Destination file path for the .conf output.

        Returns:
            The absolute path of the written file.

        Raises:
            OSError: If the output file cannot be written.
        """
        lines: list[str] = [SEC_HEADER]
        lines.append(self._generation_comment())
        lines.append(f"# Total chains: {len(chains)}")
        lines.append("")

        for chain_idx, chain in enumerate(chains, start=1):
            severity = chain.severity if isinstance(chain.severity, str) else chain.severity.value
            techniques = ", ".join(chain.mitre_techniques) if chain.mitre_techniques else "N/A"

            lines.append("#" + "=" * 77)
            lines.append(f"# CHAIN {chain_idx}/{len(chains)}: {chain.name}")
            lines.append(f"# Severity : {severity.upper()}")
            lines.append(f"# MITRE    : {techniques}")
            lines.append(f"# Events   : {len(chain.events)}")
            lines.append("#" + "=" * 77)
            lines.append("")

            event_blocks: list[tuple[str, str]] = []
            for step_idx, event in enumerate(chain.events, start=1):
                lines.append(f"# Chain {chain_idx} / Step {step_idx}: {event.event_type} on {event.target}")
                lines.extend(self._single_rule(event, chain_name=chain.name))
                lines.append("")
                tool = event.tool if isinstance(event.tool, str) else event.tool.value
                etype = event.event_type if isinstance(event.event_type, str) else event.event_type.value
                event_blocks.append((
                    self._build_pattern(tool, etype, event.target),
                    self._rule_desc(event, chain.name),
                ))

            lines.append(f"# Chain {chain_idx} completion rule")
            lines.extend(self._eventgroup_rule(chain, event_blocks))
            lines.append("")

        return self._write(output_path, lines)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _single_rule(
        self,
        event: RedSecEvent,
        chain_name: str = "",
    ) -> list[str]:
        """Build a SEC ``type=Single`` rule block for one event.

        The pattern is a RegExp anchored on tool, event_type, and target
        so it matches the SEC log line format emitted by
        ``RedSecEvent.to_sec_line()``.

        Args:
            event: The event to represent as a SEC rule.
            chain_name: Optional chain name included in the action echo.

        Returns:
            List of strings, one per line of the SEC rule block
            (no trailing newline on each string).
        """
        tool = event.tool if isinstance(event.tool, str) else event.tool.value
        event_type = event.event_type if isinstance(event.event_type, str) else event.event_type.value
        technique = event.mitre_technique or "N/A"
        chain_label = chain_name if chain_name else "standalone"

        pattern = self._build_pattern(tool, event_type, event.target)
        desc = self._rule_desc(event, chain_label)
        action_msg = (
            f"CHAIN: {chain_label} | EVENT: {event_type} "
            f"| TARGET: {event.target} | MITRE: {technique}"
        )

        return [
            "type=Single",
            "ptype=RegExp",
            f"pattern={pattern}",
            f"desc={desc}",
            f"action=write - CHAIN: %0 | EVENT: {event_type} | TARGET: {event.target} | MITRE: {technique}",
        ]

    def _eventgroup_rule(
        self,
        chain: AttackChain,
        event_blocks: list[tuple[str, str]],
    ) -> list[str]:
        """Build a SEC ``type=EventGroup`` rule that fires on chain completion.

        Uses the SEC 2.9.4 multi-pattern format: the first event block
        opens with ``type=EventGroup``; each subsequent block is preceded
        by a bare ``and`` line.  The ``window`` and ``action`` keywords
        follow the last block.

        Args:
            chain: The AttackChain whose completion is being detected.
            event_blocks: Ordered list of ``(pattern, desc)`` tuples from
                          the per-event Single rules.

        Returns:
            List of strings forming the SEC EventGroup rule block.
        """
        rule: list[str] = ["type=EventGroup"]
        for i, (pattern, desc) in enumerate(event_blocks):
            if i > 0:
                rule.append("and")
            rule.append("ptype=RegExp")
            rule.append(f"pattern={pattern}")
            rule.append(f"desc={desc}")
        rule.append("window=600")
        rule.append(f"action=write - REDSEC CHAIN COMPLETE: {chain.name}")
        return rule

    def _build_pattern(self, tool: str, event_type: str, target: str) -> str:
        """Build a RegExp pattern matching a SEC log line for this event.

        The pattern is intentionally broad on the timestamp (any prefix)
        but anchored on tool, event_type, and target so it is specific
        enough to avoid false positives from unrelated log lines.

        Args:
            tool: Tool name string (e.g. ``"nmap"``).
            event_type: Event type string (e.g. ``"port_scan"``).
            target: Target IP or domain (e.g. ``"192.168.1.1"``).

        Returns:
            A RegExp string suitable for SEC's ``pattern=`` field.
        """
        return (
            r"\S+ "
            + re.escape(tool)
            + r" "
            + re.escape(event_type)
            + r" "
            + re.escape(target)
        )

    def _rule_desc(self, event: RedSecEvent, chain_name: str) -> str:
        """Return the ``desc=`` identifier string for an event's Single rule.

        The desc is used as the EventGroup sub-pattern reference, so it
        must be unique enough to identify the rule unambiguously.

        Args:
            event: Source event.
            chain_name: Chain or context label.

        Returns:
            A compact descriptor string with no special characters.
        """
        tool = event.tool if isinstance(event.tool, str) else event.tool.value
        event_type = event.event_type if isinstance(event.event_type, str) else event.event_type.value
        return f"redsec_{_safe_label(chain_name)}_{tool}_{event_type}_{event.id[:8]}"

    def _generation_comment(self) -> str:
        """Return a single-line comment with the UTC generation timestamp.

        Returns:
            Comment string in the form ``# Generated at: <ISO-8601>``.
        """
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        return f"# Generated at: {ts}"

    def _write(self, output_path: str, lines: list[str]) -> str:
        """Write a list of lines to a file and return its absolute path.

        The parent directory is created if it does not exist.

        Args:
            output_path: Destination file path.
            lines: Lines to write (no trailing newline required per line).

        Returns:
            Absolute path of the written file.

        Raises:
            OSError: If the file cannot be written.
        """
        abs_path = os.path.abspath(output_path)
        parent = os.path.dirname(abs_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
            fh.write("\n")
        return abs_path


def _safe_label(text: str) -> str:
    """Convert a human-readable string into a safe SEC label (no spaces/specials).

    Args:
        text: Input string, e.g. a chain name like ``"Full Attack Chain"``.

    Returns:
        Uppercase alphanumeric-and-underscore string, e.g. ``"FULL_ATTACK_CHAIN"``.
    """
    return re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_").upper()
